### ISSUE TITLE
docs: set custom multisend contract address

### ISSUE THREAD

**Issue by 0x8f701** [gnosis/ethers-multisend#5]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / logs**
If applicable, add screenshots and/or logs to help explain your problem.

**Relevant environment details:**
 - Browser [e.g. chrome 22, safari]
 - Node version [e.g. 14.17.4]
 - etc

**Additional context**

**Comment by jfschwarz** [comment]
@GopherJ Actually this is already possible via the second argument to `encodeMulti`, see here: https://github.com/gnosis/ethers-multisend/blob/main/src/encodeMulti.ts#L35

I realized that this is missing in the README, though. So thank you for pointing us to it.

**Comment by jfschwarz** [comment]
closed in bd5a46152b336dd2e597fd5df1e5fea5f6810688
